### ISSUE TITLE
Double-quote character as search term causes Lucene error

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ppd-explorer#71]
Entering a single double-quote character as a search term causes a search error

**Comment by bwm-epimorphics** [comment]
Confirmed no longer causes a lucene error.

The error page that comes back could be improved.  It begins with the "We're very sorry, but the query you have just run did not complete. Reasons for this are commonly due to large queries exceeding the time limit, or the result set being too large to transmit." with the more specific error message following.

**Comment by ijdickinson** [comment]
That is the error page design approved by the client. Changing it would mean going back to Lorna with a proposal. Since we're concerned with a minor edge case, I can't see that the gain is worth the disruption.
