### ISSUE TITLE
click on transaction link button reveals different results in dev

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ppd-explorer#76]
Not sure if this is a set up issue. 
If you click on the link in the search results (next to the price) to reveal the transaction details in live you see the full details for that transaction.
In dev you do not.

**Comment by ijdickinson** [comment]
This is just an artefact of running on dev. The link to the transaction details uses the full URI of the transaction, which is rooted in the domain name `landregistry.data.gov.uk`. However, since the test data is only on the dev server, not the production server, the URI does not resolve. You can see what it would be by clicking on the link, then change `landregistry.data.gov.uk` to `lr-pres-dev.epimorphics.net`.

If we want the dev URIs to resolve, we could easily make a change to generate only relative URLs in the hyperlink. I'm not sure whether it's worth it though.

**Comment by MalcolmShazell** [comment]
tested and confirmed - no defect - test team will need to remember this when testing that functionality.
