### ISSUE TITLE
500 error accessing /app/ppd/assets/application-4fb81854e16c9cae6d7670eace4af8ed2a9a0e9eb6c07b65dc175536911bf3f9.js

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ppd-explorer#83]
The July logs contain 77309 500 errors on accessing

  /app/ppd/assets/application-4fb81854e16c9cae6d7670eace4af8ed2a9a0e9eb6c07b65dc175536911bf3f9.js

mostly from bingbot.

The referrer is /app/ppd, and I don't see any references to this URL on the current page, so presumably this is a bingbot problem.

This large number of 500 errors could mask other more significant 500 errors.  Would it be possible to have these bad requests, if that is what they are, 404 instead?

**Comment by ijdickinson** [comment]
This is Bing requesting an out-of-date JavaScript asset. The assets are all fingerprinted with a SHA1 checksum, so that they can be reliably cached. If the assets are updated, new fingerprints get generated, and the old filenames were 404-ing.

This should have been enough, but a security update to Rails meant that the request was being caught as an `ActionController::InvalidCrossOriginRequest`, which was not being recognised by my error handling code and defaulting to error 500.

I've added additional cases to the error processing code so that invalid cross-origin requests get logged as 403 Forbidden.
