### ISSUE TITLE
Enhanced request logging

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ppd-explorer#97]
For operations, it would be useful to be able to identify requests by request host and to see request parameters that are sent in the body of a POST request.  This is useful when identify the source of problematic requests.

A possible solution might be to include the rails application log a log entry per request, similar to the Apache log but including the value of the X-Forwarded-For header and the POST body in a human readable form.  It should be possible to easily filter out the request log entries, e.g. using grep, from other log entries the file.

A possibly layout suitable for logging at the beginning of the request might be:

[X-Forwarded-For] [dd/mm/yyyy]:[hh:mm:ss] [tz offset] [method] [request path and args] "[User-Agent]" [X-Request-ID]  "[human readable request body]" [marker]

If logging at the end of processing the request it may be useful to add the returned  status code and the duration of the request (in milli or micro seconds) before the marker at the end.

**Comment by ijdickinson** [comment]
@bwmcbride Given the existing logging infrastructure baked into Rails, I can't easily generate *exactly* what you suggested. But I can give the information you're asking for, just in a slightly different format.

So here's a proposal: I generate logs on one line, consisting of:

    log-severity time-ISO8601 request-id method log-body-JSON

for example (reformatted for readability, but would be one line):

    DEBUG 2019-10-10T16:35:38.349+01:00 [279b4756-325b-42c0-9c18-e5779ec2e6b0] [POST]
    {"timeTakenMS":773.0953069999999,
     "requestPath":"/search",
     "queryString":"",
     "httpUserAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0",
     "xRequestID":null,
     "xForwardedFor":null,
     "body":"utf8=%E2%9C%93&authenticity_token=G1103b4nXbO%2BVo5Fv1VG6DRANtuwPmdjVsBx2rln0FuHSFhERl9%2FTA5nnIjkJR3fDD34xgv2voBjfsEU2VQK8A%3D%3D&paon=&street=fisher+hill&town=&district=&county=&postcode=&ptype%5B%5D=lrcommon%3Adetached&ptype%5B%5D=lrcommon%3Asemi-detached&ptype%5B%5D=lrcommon%3Aterraced&ptype%5B%5D=lrcommon%3Aflat-maisonette&ptype%5B%5D=lrcommon%3AotherPropertyType&nb%5B%5D=true&nb%5B%5D=false&et%5B%5D=lrcommon%3Afreehold&et%5B%5D=lrcommon%3Aleasehold&tc%5B%5D=ppd%3AstandardPricePaidTransaction&tc%5B%5D=ppd%3AadditionalPricePaidTransaction&min_price=&max_price=&min_date=&max_date=&limit=100",
     "responseStatus":200
    }

I think the `x*` params are `null` because this is just an example from my dev machine, but it may be I need to tune the formatter to produce the right values.

My hope is that parsing a JSON body and picking out the relevant fields would be an easy thing for your log processor to do, but I can change it to generate another serialization if preferred.

**Comment by ijdickinson** [comment]
And I meant to add: I can easily add more fields to the JSON structure if there's any potentially useful info not included yet.

**Comment by bwmcbride** [comment]
That might well work.  My 'log processor' is grep and typical uses are to filter my source IP (xForwardedFor) and duration so I think that should be doable.

**Comment by ijdickinson** [comment]
We need to finalise the log format, but this will be addressed during the current infrastructure update

**Comment by ijdickinson** [comment]
This is addressed in the `json-rails-logger` gem
